main: com.clancraft.turnmanager.TurnManager
version: 0.1.4
name: TurnManager

commands:
  tm:
    description: Description.

permissions:
  tm.cycle:
    description: Allows you to access all cycle commands.
    default: op
    children:
      tm.cycle.list: true
      tm.cycle.add: true
      tm.cycle.remove: true
      tm.cycle.swap: true
  tm.cycle.list:
    description: Allows you to see the turn cycle.
    default: op
  tm.cycle.add:
    description: Allows you to add a player to the turn cycle.
    default: op
  tm.cycle.remove:
    description: Allows you to remove a player from the turn cycle.
    default: op
  tm.cycle.swap:
    description: Allows you to swap two players' turns in a cycle.
    default: op
  tm.turn:
    description: Allows you to access all turn commands.
    default: op
    children:
      tm.turn.next: true
      tm.turn.announce: true
  tm.turn.next:
    description: Allows you to advance the turn.
    default: op
  tm.turn.announce:
    description: Allows you to announce the current turn.
    default: op
  tm.timer:
    description: Allows you to access all turn  commands.
    default: op
    children:
      tm.timer.start: true
      tm.timer.stop: true
  tm.timer.start:
    description: Allows you to start the turn timer.
    default: op
  tm.timer.stop:
    description: Allows you to stop the turn timer.
    default: op